server:
  #端口
  port: 8082
spring:
  mvc:
    pathmatch:
      #springboot2.6路径匹配规则从AntPathMatcher更改为PathPatternParser
      #swagger2就不能用了,所以切换为原来的
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://1.71.129.121:3306/yeb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: NewPassWord1.
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 1800000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #redis配置
  redis:
    #服务器地址
    host: 127.0.0.1
    #端口
    port: 6379
    #默认数据库
    database: 0
    #超时时间
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最大连接阻塞等待时间,默认-1
        max-wait: 10000ms
        #最大空闲连接,默认8
        max-idle: 200
        min-idle: 5
  #rabbitMQ
  rabbitmq:
    host: 127.0.0.1
    #用户名(默认guest)
    username: guest
    #密码(默认guest)
    password: guest
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只能处理1条消息,处理完再继续下一条
        prefetch: 1
        #启动时是否默认启动容器,默认true
        auto-startup: true
        #当你的消息被拒绝时,是否重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #开启重试
        enabled: true
        #重试时间,默认1000ms
        initial-interval: 1000ms
        #重试次数,默认是3
        max-attempts: 3
        #重试的最大时间,默认10000ms
        max-interval: 10000ms
        #重试的间隔乘数,比如2.0,第一次等10s,第二次20s,第三次40s
        multiplier: 1
    #消息确认回调
    publisher-confirm-type: correlated
    #消息失败回调
    publisher-returns: true

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.example.server.entity
  configuration:
    #自动驼峰命名
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: auto
#mybatis SQL打印(方法接口所在包,不是Mapper.xml所在的包)
logging:
  level:
    com.example.server.mapper: debug
jwt:
  #JWT 存储的请求头
  tokenHeader: Authorization
  #JWT 加解密使用的秘钥
  secret: yeb-secret
  #JWT 的超期时间(60*60*24)
  expiration: 86400
  #JWT 负载中拿到的开头
  tokenHead: Bearer
