server:
  #端口
  port: 8082
spring:
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: utf-8
    password: 你自己开启smtp后获取的密钥
    username: 你自己的邮箱
    port: 25
  #rabbitMQ
  rabbitmq:
    host: 127.0.0.1
    #用户名(默认guest)
    username: guest
    #密码(默认guest)
    password: guest
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只能处理1条消息,处理完再继续下一条
        prefetch: 1
        #启动时是否默认启动容器,默认true
        auto-startup: true
        #当你的消息被拒绝时,是否重新进入队列
        default-requeue-rejected: true
        #开启手动确认
        acknowledge-mode: manual
    template:
      retry:
        #开启重试
        enabled: true
        #重试时间,默认1000ms
        initial-interval: 1000ms
        #重试次数,默认是3
        max-attempts: 3
        #重试的最大时间,默认10000ms
        max-interval: 10000ms
        #重试的间隔乘数,比如2.0,第一次等10s,第二次20s,第三次40s
        multiplier: 1
    #消息确认回调
    publisher-confirm-type: correlated
    #消息失败回调
    publisher-returns: true
  #redis配置
  redis:
    #服务器地址
    host: 127.0.0.1
    #端口
    port: 6379
    #默认数据库
    database: 0
    #超时时间
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最大连接阻塞等待时间,默认-1
        max-wait: 10000ms
        #最大空闲连接,默认8
        max-idle: 200
        min-idle: 5
